@startmindmap
* Performance
 * data
  * protocols
  * formats
  * locality
 * concepts
  * sharding
  * caching
  * reverse proxy
  * pools
   * objects
   * connection
   * thread
 * testing
  * profiling
  * monitoring
   * APM
  * debugging
  * load
 left side
 * application
  * architecture
 * optimization / metrics
  * latency
  * throughput
  * memory consumption
  * CPU
  * db query
 * hw friendly
  * memory alignment
  * using DMA

@endmindmap

